routes/web.php
    Route::post('/dmaster/mappingprogramtoopd/changenumberrecordperpage',['uses'=>'DMaster\MappingProgramToOPDController@changenumberrecordperpage','as'=>'mappingprogramtoopd.changenumberrecordperpage']);  
    Route::post('/dmaster/mappingprogramtoopd/changenumberrecordperpagecreate',['uses'=>'DMaster\MappingProgramToOPDController@changenumberrecordperpagecreate','as'=>'mappingprogramtoopd.changenumberrecordperpagecreate']);  
    Route::post('/dmaster/mappingprogramtoopd/orderby',['uses'=>'DMaster\MappingProgramToOPDController@orderby','as'=>'mappingprogramtoopd.orderby']);  
    
    //masters - sumber dana [aneka data]
    Route::resource('/dmaster/sumberdana','DMaster\SumberDanaController',['parameters'=>['sumberdana'=>'uuid']]); 
    Route::post('/dmaster/sumberdana/search',['uses'=>'DMaster\SumberDanaController@search','as'=>'sumberdana.search']);          
    Route::get('/dmaster/sumberdana/paginate/{id}',['uses'=>'DMaster\SumberDanaController@paginate','as'=>'sumberdana.paginate']);              
    Route::post('/dmaster/sumberdana/changenumberrecordperpage',['uses'=>'DMaster\SumberDanaController@changenumberrecordperpage','as'=>'sumberdana.changenumberrecordperpage']);  
    Route::post('/dmaster/sumberdana/orderby',['uses'=>'DMaster\SumberDanaController@orderby','as'=>'sumberdana.orderby']); 

    //masters - pagu anggaran OPD/SKPD [aneka data] 
    Route::resource('/dmaster/paguanggaranopd','DMaster\PaguAnggaranOPDController',['parameters'=>['paguanggaranopd'=>'uuid']]); 
    Route::post('/dmaster/paguanggaranopd/search',['uses'=>'DMaster\PaguAnggaranOPDController@search','as'=>'paguanggaranopd.search']);  
    Route::get('/dmaster/paguanggaranopd/paginate/{id}',['uses'=>'DMaster\PaguAnggaranOPDController@paginate','as'=>'paguanggaranopd.paginate']);              
    Route::post('/dmaster/paguanggaranopd/changenumberrecordperpage',['uses'=>'DMaster\PaguAnggaranOPDController@changenumberrecordperpage','as'=>'paguanggaranopd.changenumberrecordperpage']);  
    Route::post('/dmaster/paguanggaranopd/orderby',['uses'=>'DMaster\PaguAnggaranOPDController@orderby','as'=>'paguanggaranopd.orderby']); 
    Route::get('/dmaster/paguanggaranopd/getkodekelompokurusan/{uuid}',['uses'=>'DMaster\PaguAnggaranOPDController@getkodekelompokurusan','as'=>'paguanggaranopd.getkodekelompokurusan']); 
    
    //masters - pagu anggaran anggota dewan [aneka data] 
    Route::resource('/dmaster/paguanggarandewan','DMaster\PaguAnggaranDewanController',['parameters'=>['paguanggarandewan'=>'uuid']]); 
    Route::post('/dmaster/paguanggarandewan/search',['uses'=>'DMaster\PaguAnggaranDewanController@search','as'=>'paguanggarandewan.search']);  
    Route::get('/dmaster/paguanggarandewan/paginate/{id}',['uses'=>'DMaster\PaguAnggaranDewanController@paginate','as'=>'paguanggarandewan.paginate']);              
    Route::post('/dmaster/paguanggarandewan/changenumberrecordperpage',['uses'=>'DMaster\PaguAnggaranDewanController@changenumberrecordperpage','as'=>'paguanggarandewan.changenumberrecordperpage']);  
    Route::post('/dmaster/paguanggarandewan/orderby',['uses'=>'DMaster\PaguAnggaranDewanController@orderby','as'=>'paguanggarandewan.orderby']); 
    Route::get('/dmaster/paguanggarandewan/getkodekelompokurusan/{uuid}',['uses'=>'DMaster\PaguAnggaranDewanController@getkodekelompokurusan','as'=>'paguanggarandewan.getkodekelompokurusan']); 
    
    //RPJMD - Visi
    Route::resource('/perencanaan/rpjmd/rpjmdvisi','RPJMD\RPJMDVisiController',['parameters'=>['rpjmdvisi'=>'uuid']]); 
    Route::post('/perencanaan/rpjmd/rpjmdvisi/search',['uses'=>'RPJMD\RPJMDVisiController@search','as'=>'rpjmdvisi.search']); 
    Route::get('/perencanaan/rpjmd/rpjmdvisi/paginate/{id}',['uses'=>'RPJMD\RPJMDVisiController@paginate','as'=>'rpjmdvisi.paginate']);              
    Route::post('/perencanaan/rpjmd/rpjmdvisi/changenumberrecordperpage',['uses'=>'RPJMD\RPJMDVisiController@changenumberrecordperpage','as'=>'rpjmdvisi.changenumberrecordperpage']);  
    Route::post('/perencanaan/rpjmd/rpjmdvisi/orderby',['uses'=>'RPJMD\RPJMDVisiController@orderby','as'=>'rpjmdvisi.orderby']); 

    //RPJMD - Misi
    Route::resource('/perencanaan/rpjmd/rpjmdmisi','RPJMD\RPJMDMisiController',['parameters'=>['rpjmdmisi'=>'uuid']]); 
    Route::get('/perencanaan/rpjmd/rpjmdmisi/getkodemisi/{uuid}',['uses'=>'RPJMD\RPJMDMisiController@getkodemisi','as'=>'rpjmdmisi.getkodemisi']);              
    Route::post('/perencanaan/rpjmd/rpjmdmisi/search',['uses'=>'RPJMD\RPJMDMisiController@search','as'=>'rpjmdmisi.search']); 
    Route::get('/perencanaan/rpjmd/rpjmdmisi/paginate/{id}',['uses'=>'RPJMD\RPJMDMisiController@paginate','as'=>'rpjmdmisi.paginate']);              
    Route::post('/perencanaan/rpjmd/rpjmdmisi/changenumberrecordperpage',['uses'=>'RPJMD\RPJMDMisiController@changenumberrecordperpage','as'=>'rpjmdmisi.changenumberrecordperpage']);  
    Route::post('/perencanaan/rpjmd/rpjmdmisi/orderby',['uses'=>'RPJMD\RPJMDMisiController@orderby','as'=>'rpjmdmisi.orderby']); 

    //RPJMD - Tujuan. getdaftartujuanrpjmd yang jadi uuid-nya dari rpjmdmisi
    Route::resource('/perencanaan/rpjmd/rpjmdtujuan','RPJMD\RPJMDTujuanController',['parameters'=>['rpjmdtujuan'=>'uuid']]); 
    Route::post('/perencanaan/rpjmd/rpjmdtujuan/store1',['uses'=>'RPJMD\RPJMDTujuanController@store1','as'=>'rpjmdtujuan.store1']);      
    Route::get('/perencanaan/rpjmd/rpjmdtujuan/getdaftartujuanrpjmd/{uuid}',['uses'=>'RPJMD\RPJMDTujuanController@getdaftartujuanrpjmd','as'=>'rpjmdtujuan.getdaftartujuanrpjmd']);              
    Route::get('/perencanaan/rpjmd/rpjmdtujuan/getkodetujuan/{uuid}',['uses'=>'RPJMD\RPJMDTujuanController@getkodetujuan','as'=>'rpjmdtujuan.getkodetujuan']);              
    Route::get('/perencanaan/rpjmd/rpjmdtujuan/edit1/{uuid}',['uses'=>'RPJMD\RPJMDTujuanController@edit1','as'=>'rpjmdtujuan.edit1']);  
    Route::put('/perencanaan/rpjmd/rpjmdtujuan/update1/{uuid}',['uses'=>'RPJMD\RPJMDTujuanController@update1','as'=>'rpjmdtujuan.update1']);  
    Route::post('/perencanaan/rpjmd/rpjmdtujuan/search',['uses'=>'RPJMD\RPJMDTujuanController@search','as'=>'rpjmdtujuan.search']); 
    Route::get('/perencanaan/rpjmd/rpjmdtujuan/paginate/{id}',['uses'=>'RPJMD\RPJMDTujuanController@paginate','as'=>'rpjmdtujuan.paginate']);                  
    Route::post('/perencanaan/rpjmd/rpjmdtujuan/changenumberrecordperpage',['uses'=>'RPJMD\RPJMDTujuanController@changenumberrecordperpage','as'=>'rpjmdtujuan.changenumberrecordperpage']);  
    Route::post('/perencanaan/rpjmd/rpjmdtujuan/orderby',['uses'=>'RPJMD\RPJMDTujuanController@orderby','as'=>'rpjmdtujuan.orderby']); 
    
    //RPJMD - Sasaran getdaftarsasaranrpjmd yang jadi uuid-nya dari rpjmdtujuan
    Route::resource('/perencanaan/rpjmd/rpjmdsasaran','RPJMD\RPJMDSasaranController',['parameters'=>['rpjmdsasaran'=>'uuid']]); 
    Route::post('/perencanaan/rpjmd/rpjmdsasaran/store1',['uses'=>'RPJMD\RPJMDSasaranController@store1','as'=>'rpjmdsasaran.store1']);
    Route::get('/perencanaan/rpjmd/rpjmdsasaran/getdaftarsasaranrpjmd/{uuid}',['uses'=>'RPJMD\RPJMDSasaranController@getdaftarsasaranrpjmd','as'=>'rpjmdsasaran.getdaftarsasaranrpjmd']);                
    Route::get('/perencanaan/rpjmd/rpjmdsasaran/getkodesasaran/{uuid}',['uses'=>'RPJMD\RPJMDSasaranController@getkodesasaran','as'=>'rpjmdsasaran.getkodesasaran']);              
    Route::get('/perencanaan/rpjmd/rpjmdsasaran/edit1/{uuid}',['uses'=>'RPJMD\RPJMDSasaranController@edit1','as'=>'rpjmdsasaran.edit1']);  
    Route::put('/perencanaan/rpjmd/rpjmdsasaran/update1/{uuid}',['uses'=>'RPJMD\RPJMDSasaranController@update1','as'=>'rpjmdsasaran.update1']);  
    Route::post('/perencanaan/rpjmd/rpjmdsasaran/search',['uses'=>'RPJMD\RPJMDSasaranController@search','as'=>'rpjmdsasaran.search']); 
    Route::get('/perencanaan/rpjmd/rpjmdsasaran/paginate/{id}',['uses'=>'RPJMD\RPJMDSasaranController@paginate','as'=>'rpjmdsasaran.paginate']);              
    Route::post('/perencanaan/rpjmd/rpjmdsasaran/changenumberrecordperpage',['uses'=>'RPJMD\RPJMDSasaranController@changenumberrecordperpage','as'=>'rpjmdsasaran.changenumberrecordperpage']);  
    Route::post('/perencanaan/rpjmd/rpjmdsasaran/orderby',['uses'=>'RPJMD\RPJMDSasaranController@orderby','as'=>'rpjmdsasaran.orderby']); 

    //RPJMD - Strategi
    Route::resource('/perencanaan/rpjmd/rpjmdstrategi','RPJMD\RPJMDStrategiController',['parameters'=>['rpjmdstrategi'=>'uuid']]); 
    Route::post('/perencanaan/rpjmd/rpjmdstrategi/search',['uses'=>'RPJMD\RPJMDStrategiController@search','as'=>'rpjmdstrategi.search']); 
    Route::get('/perencanaan/rpjmd/rpjmdstrategi/getkodestrategi/{uuid}',['uses'=>'RPJMD\RPJMDStrategiController@getkodestrategi','as'=>'rpjmdstrategi.getkodestrategi']);              
    Route::get('/perencanaan/rpjmd/rpjmdstrategi/paginate/{id}',['uses'=>'RPJMD\RPJMDStrategiController@paginate','as'=>'rpjmdstrategi.paginate']);              
    Route::post('/perencanaan/rpjmd/rpjmdstrategi/changenumberrecordperpage',['uses'=>'RPJMD\RPJMDStrategiController@changenumberrecordperpage','as'=>'rpjmdstrategi.changenumberrecordperpage']);  
    Route::post('/perencanaan/rpjmd/rpjmdstrategi/orderby',['uses'=>'RPJMD\RPJMDStrategiController@orderby','as'=>'rpjmdstrategi.orderby']); 

    //RPJMD - Kebijakan
    Route::resource('/perencanaan/rpjmd/rpjmdkebijakan','RPJMD\RPJMDKebijakanController',['parameters'=>['rpjmdkebijakan'=>'uuid']]); 
    Route::post('/perencanaan/rpjmd/rpjmdkebijakan/store1',['uses'=>'RPJMD\RPJMDKebijakanController@store1','as'=>'rpjmdkebijakan.store1']);  
    Route::get('/perencanaan/rpjmd/rpjmdkebijakan/getkodekebijakan/{uuid}',['uses'=>'RPJMD\RPJMDKebijakanController@getkodekebijakan','as'=>'rpjmdkebijakan.getkodekebijakan']);              
    Route::post('/perencanaan/rpjmd/rpjmdkebijakan/filter',['uses'=>'RPJMD\RPJMDKebijakanController@filter','as'=>'rpjmdkebijakan.filter']);              

app/Models/RPJMD/RPJMDIndikatorKinerjaModel.php
<?php

namespace App\Models\RPJMD;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class RPJMDIndikatorKinerjaModel extends Model {
    use LogsActivity;

     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'trIndikatorKinerja';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'IndikatorKinerjaID',
        'OrgIDRPJMD', 
        'UrsID', 
        'PrgID',    
        'NamaIndikator',    
        'Satuan',    
        'KondisiAwal',    
        'TargetN1',
        'TargetN2',
        'TargetN3',
        'TargetN4',
        'TargetN5',
        'PaguDanaN1',
        'PaguDanaN2',
        'PaguDanaN3',
        'PaguDanaN4',
        'PaguDanaN5',
        'KondisiAkhirTarget',        
        'KondisiAkhirPaguDana',        
        'Descr',
        'TA',
        'Locked'
    ];
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'IndikatorKinerjaID';
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = false;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    protected static $logName = 'RPJMDIndikatorKinerjaController';
    /**
     * log the changed attributes for all these events 
     */
    protected static $logAttributes = ['IndikatorKinerjaID', 'NamaIndikator'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];

    public static function getDaftarIndikatorKinerja($UrsID,$PrgID=null,$OrgID=null,$prepend=true)
    {   
        $data = RPJMDIndikatorKinerjaModel::where('UrsID',$UrsID)
                                            ->where('TA_N',config('eplanning.rpjmd_tahun_mulai'));

        if ($PrgID != null)
        {
            $data = $data->where('PrgID',$PrgID);
        }
        if ($OrgID != null)
        {
            $data = $data->where('OrgID',$OrgID);
        }
        
        $daftar_indikator = $prepend==true ? $data->get()
                ->pluck('NamaIndikator','IndikatorKinerjaID')
                ->prepend('DAFTAR INDIKATOR KINERJA','none')
                ->toArray()
                :
                $data->get()
                ->pluck('NamaIndikator','IndikatorKinerjaID')
                ->toArray();
        
        return $daftar_indikator;
    }
    public static function getIndikatorKinerjaByID($IndikatorKinerjaID,$ta)
    {
        $data = RPJMDIndikatorKinerjaModel::find($IndikatorKinerjaID);
        $data_indikator=null;
        if (!is_null($data) )  
        {   
            $tahun_n=($ta-\HelperKegiatan::getRPJMDTahunMulai());
            $target_n=$tahun_n >0 ?"TargetN$tahun_n":'TargetN1';
            $pagudana_n=$tahun_n>0?"PaguDanaN$tahun_n":'PaguDanaN1';
            $data_indikator=[
                'NamaIndikator'=>$data->NamaIndikator,
                'TargetAngka'=>$data[$target_n],
                'PaguDana'=>$data[$pagudana_n]
            ];
        }
        return $data_indikator;
    }
}

app/Models/RPJMD/RPJMDKebijakanModel.php
<?php

namespace App\Models\RPJMD;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class RPJMDKebijakanModel extends Model {
    use LogsActivity;
    /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'tmPrioritasKebijakanKab';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'PrioritasKebijakanKabID', 'PrioritasStrategiKabID', 'Kd_Kebijakan', 'Nm_Kebijakan', 'Descr', 'TA'
    ];
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'PrioritasKebijakanKabID';
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = false;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    protected static $logName = 'RPJMDKebijakanController';
    /**
     * log the changed attributes for all these events 
     */
    protected static $logAttributes = ['PrioritasKebijakanKabID', 'Kd_Kebijakan', 'Nm_Kebijakan'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];

    public static function getDaftarKebijakan($ta,$prepend=true)
    {
        $r=RPJMDKebijakanModel::select(\DB::raw('
                                "PrioritasKebijakanKabID",
                                CONCAT(
                                \'[\',
                                "Kd_PrioritasKab",
                                \'.\',
                                "Kd_Tujuan",
                                \'.\',
                                "Kd_Sasaran",
                                \'.\',
                                "Kd_Strategi",
                                \'.\',
                                "Kd_Kebijakan",
                                \'] \',
                                "Nm_Kebijakan"
                                ) AS "Nm_Kebijakan"'))
                                ->join('tmPrioritasStrategiKab','tmPrioritasKebijakanKab.PrioritasStrategiKabID','tmPrioritasStrategiKab.PrioritasStrategiKabID')
                                ->join('tmPrioritasSasaranKab','tmPrioritasSasaranKab.PrioritasSasaranKabID','tmPrioritasStrategiKab.PrioritasSasaranKabID')
                                ->join('tmPrioritasTujuanKab','tmPrioritasTujuanKab.PrioritasTujuanKabID','tmPrioritasSasaranKab.PrioritasTujuanKabID')
                                ->join('tmPrioritasKab','tmPrioritasKab.PrioritasKabID','tmPrioritasTujuanKab.PrioritasKabID')
                                ->where('tmPrioritasStrategiKab.TA',$ta)
                                ->orderBy('Kd_PrioritasKab')
                                ->orderBy('Kd_Tujuan')
                                ->orderBy('Kd_Sasaran')
                                ->orderBy('Kd_Strategi')
                                ->get();

        $daftar_kebijakan=$prepend == true 
                                        ?
                                            $r->pluck('Nm_Kebijakan','PrioritasKebijakanKabID')
                                            ->prepend('DAFTAR KEBIJAKAN RPJMD')
                                            ->toArray()
                                        :
                                        $r->pluck('Nm_Kebijakan','PrioritasKebijakanKabID')
                                            ->toArray();
       
        return $daftar_kebijakan;
    }
}

resources/views/pages/limitless/rpjmd/rpjmdkebijakan/datatable.blade.php
<div class="panel panel-flat border-top-lg border-top-info border-bottom-info">
    <div class="panel-heading">
        <div class="panel-title">
            <h6 class="panel-title">&nbsp;</h6>
        </div>
        <div class="heading-elements">
            {!! Form::open(['url'=>'#','method'=>'post','class'=>'heading-form','id'=>'frmheading','name'=>'frmheading'])!!} 
                <div class="form-group">
                    {!!Form::select('numberRecordPerPage',['1'=>1,'5'=>5,'10'=>10,'15'=>15,'30'=>30,'50'=>50],$numberRecordPerPage,['id'=>'numberRecordPerPage','class'=>'form-control','style'=>'width:70px'])!!}                        
                </div> 
                <div class="form-group">
                    <a href="{!!route('rpjmdkebijakan.create')!!}" class="btn btn-info btn-xs" title="Tambah RPJMD Misi">
                        <i class="icon-googleplus5"></i>
                    </a>
                </div> 
            {!! Form::close()!!}
        </div>       
    </div>
    @if (count($data) > 0)
    <div class="table-responsive"> 
        <table id="data" class="table table-striped table-hover">
            <thead>
                <tr class="bg-teal-700">
                    <th width="55">NO</th>
                    <th width="150">
                        KODE KEBIJAKAN  
                    </th> 
                    <th>
                        NAMA KEBIJAKAN  
                    </th> 
                    <th width="100">JUMLAH PROGRAM</th>
                    <th width="100">TA</th>
                    <th width="100">AKSI</th>
                </tr>
            </thead>
            <tbody>                    
            @foreach ($data as $key=>$item)
                <tr>
                    <td>
                        {{ ($data->currentpage()-1) * $data->perpage() + $key + 1 }}    
                    </td>                  
                    <td>{{$item->Kd_Kebijakan}}</td>
                    <td>{{$item->Nm_Kebijakan}}</td>
                    <td>{{DB::table('tmPrioritasProgramKebijakan')->where('PrioritasKebijakanKabID',$item->PrioritasKebijakanKabID)->count()}}</td>
                    <td>{{$item->TA}}</td>
                    <td>
                        <ul class="icons-list">
                            <li class="text-primary-600">
                                <a class="btnShow" href="{{route('rpjmdkebijakan.show',['uuid'=>$item->PrioritasKebijakanKabID])}}" title="Detail Data RPJMD Kebijakan">
                                    <i class='icon-eye'></i>
                                </a>  
                            </li>
                            <li class="text-primary-600">
                                <a class="btnEdit" href="{{route('rpjmdkebijakan.edit',['uuid'=>$item->PrioritasKebijakanKabID])}}" title="Ubah Data RPJMD Kebijakan">
                                    <i class='icon-pencil7'></i>
                                </a>  
                            </li>
                            <li class="text-danger-600">
                                <a class="btnDelete" href="javascript:;" title="Hapus Data RPJMD Kebijakan" data-id="{{$item->PrioritasKebijakanKabID}}" data-url="{{route('rpjmdkebijakan.index')}}">
                                    <i class='icon-trash'></i>
                                </a> 
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr class="text-center info">
                    <td colspan="6">
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>PRIORITASKEBIJAKANKABID:</strong>
                            {{$item->PrioritasKebijakanKabID}}
                        </span> 
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>PRIORITASSTRATEGIKABID:</strong>
                            {{$item->PrioritasStrategiKabID}}
                        </span>                                                                      
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>CREATED:</strong>
                            {{Helper::tanggal('d/m/Y H:m',$item->created_at)}}
                        </span>
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>UPDATED:</strong>
                            {{Helper::tanggal('d/m/Y H:m',$item->updated_at)}}
                        </span>
                    </td>
                </tr>
            @endforeach                    
            </tbody>
        </table>               
    </div>
    <div class="panel-body border-top-info text-center" id="paginations">
        {{$data->links('layouts.limitless.l_pagination')}}               
    </div>
    @else
    <div class="panel-body">
        <div class="alert alert-info alert-styled-left alert-bordered">
            <span class="text-semibold">Info!</span>
            Belum ada data yang bisa ditampilkan.
        </div>
    </div>   
    @endif            
</div>

resources/views/pages/limitless/rpjmd/rpjmdkebijakan/datatableprogramkebijakan.blade.php
<div class="panel-heading">
    <div class="panel-title">
        <h5>DAFTAR PROGRAM KEBIJAKAN</h5>
    </div>
    <div class="heading-elements">
        
    </div>
</div>
@if (count($dataprogramkebijakan) > 0)
<div class="table-responsive"> 
    <table id="data" class="table table-striped table-hover" style="font-size:11px">
        <thead>
            <tr class="bg-teal-700">
                <th width="55">NO</th>     
                <th>NAMA PROGRAM</th>                
                <th>NAMA URUSAN</th>                                
                <th width="70">TA</th>                                     
                <th width="100">AKSI</th>
            </tr>
        </thead>
        <tbody>                    
        @foreach ($dataprogramkebijakan as $key=>$item)
            <tr>
                <td>
                    {{ $key + 1 }}    
                </td>
                <td>{{$item->PrgNm}}</td>
                <td>{{$item->Nm_Bidang}}</td>                                        
                <td>{{$item->TA}}</td>                                    
                <td>                    
                    <ul class="icons-list">
                        <li class="text-danger-600">
                            <a class="btnDelete" href="javascript:;" title="Hapus Data Indikator" data-id="{{$item->ProgramKebijakanID}}" data-url="{{route(Helper::getNameOfPage('index'))}}">
                                <i class='icon-trash'></i>
                            </a> 
                        </li>
                    </ul>                    
                </td>
            </tr>
            <tr class="text-center info">
                <td colspan="11">
                    <span class="label label-warning label-rounded" style="text-transform: none">
                        <strong>PROGRAMKEBIJAKANID:</strong>
                        {{$item->ProgramKebijakanID}}
                    </span>
                    <span class="label label-warning label-rounded">
                        <strong>KET:</strong>
                        {{empty($item->Descr)?'-':$item->Descr}}
                    </span>
                    <span class="label label-warning label-rounded" style="text-transform: none">
                        <strong>CREATED:</strong>
                        {{Helper::tanggal('d/m/Y H:m',$item->created_at)}}
                    </span>
                    <span class="label label-warning label-rounded" style="text-transform: none">
                        <strong>UPDATED:</strong>
                        {{Helper::tanggal('d/m/Y H:m',$item->updated_at)}}
                    </span>
                </td>
            </tr>
        @endforeach                    
        </tbody>
    </table>       
</div>       
@else
<div class="panel-body">
    <div class="alert alert-info alert-styled-left alert-bordered">
        <span class="text-semibold">Info!</span>
        Belum ada data yang bisa ditampilkan.
    </div>
</div>   
@endif               

resources/views/pages/limitless/rpjmd/rpjmdkebijakan/error.blade.php
@extends('layouts.limitless.l_main')
@section('page_title')
    RPJMD PRIORITAS / ARAH KEBIJAKAN
@endsection
@section('page_header')
    <i class="icon-price-tag position-left"></i>
    <span class="text-semibold">
        RPJMD PRIORITAS / ARAH KEBIJAKAN  PERIODE {{HelperKegiatan::getRPJMDTahunMulai()}} - {{HelperKegiatan::getRPJMDTahunAkhir()+1}}
    </span>
@endsection
@section('page_info')
    @include('pages.limitless.rpjmd.rpjmdkebijakan.info')
@endsection
@section('page_breadcrumb')
    <li><a href="#">PERENCANAAN</a></li>
    <li><a href="#">RPJMD</a></li>
    <li><a href="{!!route('rpjmdkebijakan.index')!!}">PRIORITAS / ARAH KEBIJAKAN</a></li>
    <li class="active">ERROR</li>
@endsection
@section('page_content')
<div class="alert alert-danger alert-styled-left alert-bordered">
    <button type="button" class="close" onclick="location.href='{{route('rpjmdkebijakan.index')}}'">×</button>
    {{$errormessage}}
</div>
@endsection