routes/web.php
<?php

//disable halaman register [pendaftaran]
Auth::routes(['register' => false]);

Route::get('/',['uses'=>'FrontendController@welcome','as'=>'frontend.index']);
Route::get('/logout',['uses'=>'Auth\LoginController@logout','as'=>'logout']);
Route::group (['prefix'=>'admin','middleware'=>['disablepreventback','web', 'auth']],function() {     
    Route::get('/',['uses'=>'DashboardController@index','as'=>'dashboard.index']);  
    Route::post('/filter',['uses'=>'DashboardController@filter','as'=>'dashboard.filter']);                  

    // Dashboard -  Rekap Pagu Indikatif OPD (Pra Renja, Rakor Bidang, Forum OPD, Musrenbang Kabupaten, Verifikasi TAPD, dan Pembahasan RKPD)
    Route::resource('/dashboard/rekappaguindikatifopd','Report\RekapPaguIndikatifOPDController',[
                                                                                                    'parameters'=>['rekappaguindikatifopd'=>'uuid'],
                                                                                                    'only'=>['index','store','update']
                                                                                                ]); 
    Route::post('/dashboard/rekappaguindikatifopd/orderby',['uses'=>'Report\RekapPaguIndikatifOPDController@orderby','as'=>'rekappaguindikatifopd.orderby']); 
    Route::get('/dashboard/rekappaguindikatifopd/printtoexcel',['uses'=>'Report\RekapPaguIndikatifOPDController@printtoexcel','as'=>'rekappaguindikatifopd.printtoexcel']); 
    
    // Dashboard -  Rekap Pagu RKPD OPD
    Route::resource('/dashboard/rekappagurkpdopd','Report\RekapPaguRKPDOPDController',[
                                                                                    'parameters'=>['rekappagurkpdopd'=>'uuid'],
                                                                                    'only'=>['index','store','update']
                                                                                ]); 
    Route::post('/dashboard/rekappagurkpdopd/orderby',['uses'=>'Report\RekapPaguRKPDOPDController@orderby','as'=>'rekappagurkpdopd.orderby']); 
    Route::get('/dashboard/rekappagurkpdopd/printtoexcel',['uses'=>'Report\RekapPaguRKPDOPDController@printtoexcel','as'=>'rekappagurkpdopd.printtoexcel']); 
    
    //RAPAT PEMBAHASAN TAPD
    Route::resource('/rapat','RapatController',['parameters'=>['rapat'=>'uuid']]); 
    Route::post('/rapat/search',['uses'=>'RapatController@search','as'=>'rapat.search']); 
    Route::post('/rapat/filter',['uses'=>'RapatController@filter','as'=>'rapat.filter']);                  
    Route::get('/rapat/paginate/{id}',['uses'=>'RapatController@paginate','as'=>'rapat.paginate']);              
    Route::post('/rapat/changenumberrecordperpage',['uses'=>'RapatController@changenumberrecordperpage','as'=>'rapat.changenumberrecordperpage']);  
    Route::post('/rapat/orderby',['uses'=>'RapatController@orderby','as'=>'rapat.orderby']);
    Route::get('/rapat/printtoword/{uuid}',['uses'=>'RapatController@printtoword','as'=>'rapat.printtoword']);

    //masters - provinsi [lokasi]
    Route::resource('/dmaster/provinsi','DMaster\ProvinsiController',['parameters'=>['provinsi'=>'uuid']]); 
    Route::post('/dmaster/provinsi/search',['uses'=>'DMaster\ProvinsiController@search','as'=>'provinsi.search']);          
    Route::get('/dmaster/provinsi/paginate/{id}',['uses'=>'DMaster\ProvinsiController@paginate','as'=>'provinsi.paginate']);              
    Route::post('/dmaster/provinsi/changenumberrecordperpage',['uses'=>'DMaster\ProvinsiController@changenumberrecordperpage','as'=>'provinsi.changenumberrecordperpage']);  
    Route::post('/dmaster/provinsi/orderby',['uses'=>'DMaster\ProvinsiController@orderby','as'=>'provinsi.orderby']); 
    
    //masters - kota [lokasi]
    Route::resource('/dmaster/kota','DMaster\KotaController',['parameters'=>['kota'=>'uuid']]); 
    Route::post('/dmaster/kota/search',['uses'=>'DMaster\KotaController@search','as'=>'kota.search']);          
    Route::get('/dmaster/kota/paginate/{id}',['uses'=>'DMaster\KotaController@paginate','as'=>'kota.paginate']);              
    Route::post('/dmaster/kota/changenumberrecordperpage',['uses'=>'DMaster\KotaController@changenumberrecordperpage','as'=>'kota.changenumberrecordperpage']);  
    Route::post('/dmaster/kota/orderby',['uses'=>'DMaster\KotaController@orderby','as'=>'kota.orderby']); 

    //masters - kecamatan [lokasi]
    Route::resource('/dmaster/kecamatan','DMaster\KecamatanController',['parameters'=>['kecamatan'=>'uuid']]); 
    Route::post('/dmaster/kecamatan/search',['uses'=>'DMaster\KecamatanController@search','as'=>'kecamatan.search']);          
    Route::get('/dmaster/kecamatan/paginate/{id}',['uses'=>'DMaster\KecamatanController@paginate','as'=>'kecamatan.paginate']);              
    Route::post('/dmaster/kecamatan/changenumberrecordperpage',['uses'=>'DMaster\KecamatanController@changenumberrecordperpage','as'=>'kecamatan.changenumberrecordperpage']);  
    Route::post('/dmaster/kecamatan/orderby',['uses'=>'DMaster\KecamatanController@orderby','as'=>'kecamatan.orderby']);  
    
    //masters - desa [lokasi]
    Route::resource('/dmaster/desa','DMaster\DesaController',['parameters'=>['desa'=>'uuid']]); 
    Route::post('/dmaster/desa/search',['uses'=>'DMaster\DesaController@search','as'=>'desa.search']);          
    Route::get('/dmaster/desa/paginate/{id}',['uses'=>'DMaster\DesaController@paginate','as'=>'desa.paginate']);              
    Route::post('/dmaster/desa/changenumberrecordperpage',['uses'=>'DMaster\DesaController@changenumberrecordperpage','as'=>'desa.changenumberrecordperpage']);  
    Route::post('/dmaster/desa/orderby',['uses'=>'DMaster\DesaController@orderby','as'=>'desa.orderby']);  

    //masters - tahun perencanaan dan penyerapan anggaran
    Route::resource('/dmaster/ta','DMaster\TAController',['parameters'=>['ta'=>'uuid']]); 
    Route::get('/dmaster/ta/paginate/{id}',['uses'=>'DMaster\TAController@paginate','as'=>'ta.paginate']);              
    Route::post('/dmaster/ta/changenumberrecordperpage',['uses'=>'DMaster\TAController@changenumberrecordperpage','as'=>'ta.changenumberrecordperpage']);  
    Route::post('/dmaster/ta/orderby',['uses'=>'DMaster\TAController@orderby','as'=>'ta.orderby']); 
    
    //masters - data kelompok urusan [data]
    Route::resource('/dmaster/kelompokurusan','DMaster\KelompokUrusanController',['parameters'=>['kelompokurusan'=>'uuid']]); 
    Route::get('/dmaster/kelompokurusan/paginate/{id}',['uses'=>'DMaster\KelompokUrusanController@paginate','as'=>'kelompokurusan.paginate']);              
    Route::post('/dmaster/kelompokurusan/changenumberrecordperpage',['uses'=>'DMaster\KelompokUrusanController@changenumberrecordperpage','as'=>'kelompokurusan.changenumberrecordperpage']);  
    Route::post('/dmaster/kelompokurusan/orderby',['uses'=>'DMaster\KelompokUrusanController@orderby','as'=>'kelompokurusan.orderby']); 
    Route::get('/dmaster/kelompokurusan/getkodekelompokurusan/{uuid}',['uses'=>'DMaster\KelompokUrusanController@getkodekelompokurusan','as'=>'kelompokurusan.getkodekelompokurusan']); 
    
    //masters - data urusan [data]
    Route::resource('/dmaster/urusan','DMaster\UrusanController',['parameters'=>['urusan'=>'uuid']]); 
    Route::post('/dmaster/urusan/search',['uses'=>'DMaster\UrusanController@search','as'=>'urusan.search']);          
    Route::get('/dmaster/urusan/paginate/{id}',['uses'=>'DMaster\UrusanController@paginate','as'=>'urusan.paginate']);              
    Route::post('/dmaster/urusan/changenumberrecordperpage',['uses'=>'DMaster\UrusanController@changenumberrecordperpage','as'=>'urusan.changenumberrecordperpage']);  
    Route::post('/dmaster/urusan/orderby',['uses'=>'DMaster\UrusanController@orderby','as'=>'urusan.orderby']);  
    
    //masters - data organisasi (OPD / SKPD) [data]
    Route::resource('/dmaster/organisasi','DMaster\OrganisasiController',['parameters'=>['organisasi'=>'uuid']]); 
    Route::post('/dmaster/organisasi/search',['uses'=>'DMaster\OrganisasiController@search','as'=>'organisasi.search']);  
    Route::post('/dmaster/organisasi/filter',['uses'=>'DMaster\OrganisasiController@filter','as'=>'organisasi.filter']);           
    Route::get('/dmaster/organisasi/paginate/{id}',['uses'=>'DMaster\OrganisasiController@paginate','as'=>'organisasi.paginate']);              
    Route::post('/dmaster/organisasi/changenumberrecordperpage',['uses'=>'DMaster\OrganisasiController@changenumberrecordperpage','as'=>'organisasi.changenumberrecordperpage']);  
    Route::post('/dmaster/organisasi/orderby',['uses'=>'DMaster\OrganisasiController@orderby','as'=>'organisasi.orderby']);  
    
    //masters - data sub organisasi (Unit Kerja) [data]
    Route::resource('/dmaster/suborganisasi','DMaster\SubOrganisasiController',['parameters'=>['suborganisasi'=>'uuid']]); 
    Route::post('/dmaster/suborganisasi/search',['uses'=>'DMaster\SubOrganisasiController@search','as'=>'suborganisasi.search']);  
    Route::post('/dmaster/suborganisasi/filter',['uses'=>'DMaster\SubOrganisasiController@filter','as'=>'suborganisasi.filter']);           
    Route::get('/dmaster/suborganisasi/paginate/{id}',['uses'=>'DMaster\SubOrganisasiController@paginate','as'=>'suborganisasi.paginate']);              
    Route::post('/dmaster/suborganisasi/changenumberrecordperpage',['uses'=>'DMaster\SubOrganisasiController@changenumberrecordperpage','as'=>'suborganisasi.changenumberrecordperpage']);  
    Route::post('/dmaster/suborganisasi/orderby',['uses'=>'DMaster\SubOrganisasiController@orderby','as'=>'suborganisasi.orderby']);  
    
    //masters - data program  [data]
    Route::resource('/dmaster/program','DMaster\ProgramController',['parameters'=>['program'=>'uuid']]); 
    Route::post('/dmaster/program/search',['uses'=>'DMaster\ProgramController@search','as'=>'program.search']);  

app/Models/DMaster/DesaModel.php
<?php

namespace App\Models\DMaster;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class DesaModel extends Model {
    use LogsActivity;
     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'tmPmDesa';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'PmDesaID', 
        'PmKecamatanID',
        'Kd_Desa',
        'Nm_Desa',
        'Descr',
        'TA',
    ];
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'PmDesaID';
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = false;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = false;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    // protected static $logName = 'DesaController';
    /**
     * log the changed attributes for all these events 
     */
    protected static $logAttributes = [
        'PmDesaID', 
        'PmKecamatanID',
        'Kd_Desa',
        'Nm_Desa',
        'Descr',
        'TA'
    ];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];

    public static function getDaftarDesa ($ta,$PmKecamatanID=NULL,$prepend=true) 
    {
        $q=DesaModel::where('TA',$ta);
        if ($PmKecamatanID != NULL) 
        {
            $q->where('PmKecamatanID',$PmKecamatanID);
        }
        $q->orderBy('Kd_Desa');
        $q=$q->get();   

        $daftar_desa=($prepend==true)?['none'=>'DAFTAR DESA']:[];        
        foreach ($q as $k=>$v)
        {
            $daftar_desa[$v->PmDesaID]=$v->Nm_Desa;
        } 
        return $daftar_desa;
    }    
    public function kecamatan () 
    {
        return $this->belongsTo('App\Models\DMaster\KecamatanModel','PmKecamatanID');
    }
}

app/Models/DMaster/FungsiModel.php
<?php

namespace App\Models\DMaster;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class FungsiModel extends Model {
    use LogsActivity;
     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'fungsi';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'replace_it', 'replace_it'
    ];
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'fungsi_id';
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = true;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    // protected static $logName = 'FungsiController';
    /**
     * log the changed attributes for all these events 
     */
    // protected static $logAttributes = ['replace_it', 'replace_it'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];
}

app/Models/DMaster/KecamatanModel.php
<?php

namespace App\Models\DMaster;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class KecamatanModel extends Model {
    use LogsActivity;
     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'tmPmKecamatan';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'PmKecamatanID', 'PmKotaID', 'Kd_Kecamatan', 'Nm_Kecamatan', 'Descr', 'TA'
    ];
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'PmKecamatanID';
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = false;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    // protected static $logName = 'KecamatanController';
    /**
     * log the changed attributes for all these events 
     */
    protected static $logAttributes = ['PmKecamatanID', 'PmKotaID', 'Kd_Kecamatan', 'Nm_Kecamatan', 'Descr', 'TA'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];
    public static function getDaftarKecamatan ($ta,$PmKotaID=NULL,$prepend=true) 
    {
        $r=KecamatanModel::where('TA',$ta)->orderBy('Kd_Kecamatan');
        if ($PmKotaID != NULL) 
        {
            $r=$r->where('PmKotaID',$PmKotaID);
        }
        $r=$r->get();
        
        $daftar_kecamatan=($prepend==true)?['none'=>'DAFTAR KECAMATAN']:[];        
        foreach ($r as $k=>$v)
        {
            $daftar_kecamatan[$v->PmKecamatanID]=$v->Nm_Kecamatan;
        }         
        return $daftar_kecamatan;
    }
    public function kota () 
    {
        return $this->belongsTo('App\Models\DMaster\KotaModel','PmKotaID');
    }
}

app/Models/DMaster/KelompokUrusanModel.php
<?php

namespace App\Models\DMaster;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class KelompokUrusanModel extends Model {
    use LogsActivity;
     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'tmKUrs';
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'KUrsID';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'KUrsID', 'RpjmdVisiID', 'Kd_Urusan', 'Nm_Urusan', 'Descr','TA',
    ];
    /**
     * enable auto_increment.
     *
     * @var string
     */
    public $incrementing = false;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    protected static $logName = 'KelompokUrusanController';
    /**
     * log the changed attributes for all these events 
     */
    protected static $logAttributes = ['KUrsID','Kd_Urusan', 'Nm_Urusan'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];

    public static function getKelompokUrusan ($ta,$prepend=true) 
    {
        $r=KelompokUrusanModel::where('TA',$ta)->orderBy('Kd_Urusan')->get();
        $kelompok_urusan=($prepend==true)?['none'=>'DAFTAR KELOMPOK URUSAN']:[];        
        foreach ($r as $k=>$v)
        {
            $kelompok_urusan[$v->KUrsID]=$v->Kd_Urusan.'. '.$v->Nm_Urusan;
        } 
        return $kelompok_urusan;
    }
}

resources/views/pages/limitless/dmaster/suborganisasi/datatable.blade.php
<div class="panel panel-flat border-top-lg border-top-info border-bottom-info">
    <div class="panel-heading">
        <div class="panel-title">
            <h6 class="panel-title">&nbsp;</h6>
        </div>
        <div class="heading-elements">
            {!! Form::open(['url'=>'#','method'=>'post','class'=>'heading-form','id'=>'frmheading','name'=>'frmheading'])!!} 
                <div class="form-group">
                    {!!Form::select('numberRecordPerPage',['1'=>1,'5'=>5,'10'=>10,'15'=>15,'30'=>30,'50'=>50],$numberRecordPerPage,['id'=>'numberRecordPerPage','class'=>'form-control','style'=>'width:70px'])!!}                        
                </div> 
                <div class="form-group">
                    <a href="{!!route('suborganisasi.create')!!}" class="btn btn-info btn-xs" title="Tambah ORGANISASI">
                        <i class="icon-googleplus5"></i>
                    </a>
                </div>  
            {!! Form::close()!!}          
        </div>
    </div>
    @if (count($data) > 0)
    <div class="table-responsive"> 
        <table id="data" class="table table-striped table-hover">
            <thead>
                <tr class="bg-teal-700">
                    <th width="55">NO</th>
                    <th>
                        <a class="column-sort text-white" id="col-kode_suborganisasi" data-order="{{$direction}}" href="#">
                            KODE UNIT KERJA
                        </a>                                             
                    </th> 
                    <th>
                        <a class="column-sort text-white" id="col-SOrgNm" data-order="{{$direction}}" href="#">
                            NAMA UNIT KERJA
                        </a>                                             
                    </th> 
                    <th>
                        OPD / SKPD
                    </th> 
                    <th>
                        <a class="column-sort text-white" id="col-Nm_Urusan" data-order="{{$direction}}" href="#">
                            URUSAN
                        </a>                                             
                    </th>
                    <th width="70">TA</th>
                    <th width="100">AKSI</th>
                </tr>
            </thead>
            <tbody>                    
            @foreach ($data as $key=>$item)
                <tr>
                    <td>
                        {{ ($data->currentpage()-1) * $data->perpage() + $key + 1 }}    
                    </td>                  
                    <td>{{$item->kode_suborganisasi}}</td>
                    <td>{{$item->SOrgNm}}</td>
                    <td>{{$item->OrgNm}}</td>
                    <td>{{$item->Nm_Urusan}}</td>
                    <td>{{$item->TA}}</td>
                    <td>
                        <ul class="icons-list">
                            <li class="text-primary-600">
                                <a class="btnShow" href="{{route('suborganisasi.show',['uuid'=>$item->SOrgID])}}" title="Detail Data Unit Kerja">
                                    <i class='icon-eye'></i>
                                </a>  
                            </li>
                            <li class="text-primary-600">
                                <a class="btnEdit" href="{{route('suborganisasi.edit',['uuid'=>$item->SOrgID])}}" title="Ubah Data Unit Kerja">
                                    <i class='icon-pencil7'></i>
                                </a>  
                            </li>
                            <li class="text-danger-600">
                                <a class="btnDelete" href="javascript:;" title="Hapus Data Unit Kerja" data-id="{{$item->SOrgID}}" data-url="{{route('suborganisasi.index')}}">
                                    <i class='icon-trash'></i>
                                </a> 
                            </li>
                        </ul>
                    </td>
                </tr>
				<tr class="text-center info">
                    <td colspan="7">
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>SOrgID:</strong>
                            {{$item->SOrgID}}
                        </span>
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>ORGID:</strong>
                            {{$item->OrgID}}
                        </span> 
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>ORGIDRPJMD:</strong>
                            {{$item->OrgIDRPJMD}}
                        </span> 
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>CREATED:</strong>
                            {{Helper::tanggal('d/m/Y H:m',$item->created_at)}}
                        </span>
                        <span class="label label-warning label-rounded" style="text-transform: none">
                            <strong>UPDATED:</strong>
                            {{Helper::tanggal('d/m/Y H:m',$item->updated_at)}}
                        </span>
                    </td>
                </tr>
            @endforeach                    
            </tbody>
        </table>               
    </div>
    <div class="panel-body border-top-info text-center" id="paginations">
        {{$data->links('layouts.limitless.l_pagination')}}               
    </div>
    @else
    <div class="panel-body">
        <div class="alert alert-info alert-styled-left alert-bordered">
            <span class="text-semibold">Info!</span>
            Belum ada data yang bisa ditampilkan.
        </div>
    </div>   
    @endif            
</div>

resources/views/pages/limitless/dmaster/suborganisasi/error.blade.php
@extends('layouts.limitless.l_main')
@section('page_title')
    UNIT KERJA
@endsection
@section('page_header')
    <i class="icon-office position-left"></i>
    <span class="text-semibold">
        UNIT KERJA TAHUN PERENCANAAN {{HelperKegiatan::getTahunPerencanaan()}}
    </span>
@endsection
@section('page_info')
    @include('pages.limitless.dmaster.organisasi.info')
@endsection
@section('page_breadcrumb')
    <li><a href="#">MASTERS</a></li>
    <li><a href="#">DATA</a></li>
    <li><a href="{!!route('organisasi.index')!!}">UNIT KERJA</a></li>
    <li class="active">ERROR</li>
@endsection
@section('page_content')
<div class="alert alert-danger alert-styled-left alert-bordered">
    <button type="button" class="close" onclick="location.href='{{route('kelompokurusan.index')}}'">×</button>
    {{$errormessage}}
</div>
@endsection

resources/views/pages/limitless/dmaster/suborganisasi/info.blade.php
<small class="display-block">
    Modul ini digunakan untuk melakukan pengolahan data terhadap Unit Kerja dan akan digunakan sebagai referensi.
</small>

resources/views/pages/limitless/dmaster/suborganisasi/show.blade.php
@extends('layouts.limitless.l_main')
@section('page_title')
    UNIT KERJA
@endsection
@section('page_header')
    <i class="icon-office position-left"></i>
    <span class="text-semibold"> 
        UNIT KERJA TAHUN {{HelperKegiatan::getTahunPerencanaan()}}
    </span>     
@endsection
@section('page_info')
    @include('pages.limitless.dmaster.organisasi.info')
@endsection
@section('page_breadcrumb')
    <li><a href="#">MASTERS</a></li>
    <li><a href="#">DATA</a></li>
    <li><a href="{!!route('organisasi.index')!!}">UNIT KERJA</a></li>
    <li class="active">DETAIL DATA</li>
@endsection
@section('page_content')
<div class="row">    
    <div class="col-md-12">
        <div class="panel panel-flat border-top-info border-bottom-info">
            <div class="panel-heading">
                <h5 class="panel-title"> 
                    <i class="icon-eye"></i>  DATA UNIT KERJA
                </h5>
                <div class="heading-elements">   
                    <a href="{{route('suborganisasi.edit',['uuid'=>$data->OrgID])}}" class="btn btn-primary btn-icon heading-btn btnEdit" title="Ubah Data Organisasi">
                        <i class="icon-pencil7"></i>
                    </a>
                    <a href="javascript:;" title="Hapus Data Organisasi" data-id="{{$data->OrgID}}" data-url="{{route('organisasi.index')}}" class="btn btn-danger btn-icon heading-btn btnDelete">
                        <i class='icon-trash'></i>
                    </a>
                    <a href="{!!route('suborganisasi.index')!!}" class="btn btn-default btn-icon heading-btn" title="keluar">
                        <i class="icon-close2"></i>
                    </a>            
                </div>
            </div>
            <div class="panel-body">
                <div class="row">                                      
                    <div class="col-md-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>KODE OPD/SKPD: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->kode_suborganisasi}}</p>
                                </div>                            
                            </div>                 
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>NAMA OPD/SKPD: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->SOrgNm}}</p>
                                </div>                            
                            </div>           
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>TGL. BUAT: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{Helper::tanggal('d/m/Y H:m',$data->created_at)}}</p>
                                </div>                            
                            </div>
                        </div>                        
                    </div>
                    <div class="col-md-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>URUSAN: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->Nm_Urusan}}</p>
                                </div>                            
                            </div> 
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>TA: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->TA}}</p>
                                </div>                            
                            </div>   
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>TGL. UBAH: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{Helper::tanggal('d/m/Y H:m',$data->updated_at)}}</p>
                                </div>                            
                            </div>                         
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('page_custom_js')
<script type="text/javascript">
$(document).ready(function () {
    $(".btnDelete").click(function(ev) {
        if (confirm('Apakah Anda ingin menghapus Data Organisasi ini ?')) {
            let url_ = $(this).attr("data-url");
            let id = $(this).attr("data-id");
            let token = $('meta[name="csrf-token"]').attr('content');
            $.ajax({            
                type:'post',
                url:url_+'/'+id,
                dataType: 'json',
                data: {
                    "_method": 'DELETE',
                    "_token": token,
                    "id": id,
                },
                success:function(data){ 
                    window.location.replace(url_);                        
                },
                error:function(xhr, status, error){
                    console.log('ERROR');
                    console.log(parseMessageAjaxEror(xhr, status, error));                           
                },
            });
        }
    });
    
});
</script>
@endsection