routes/web.php
    //Report - RKPD PERUBAHAN PER OPD
    Route::resource('/report/rkpd/reportrkpdperubahanopd','Report\ReportRKPDPerubahanOPDController',[
                                                                                                        'parameters'=>['reportrkpdperubahanopd'=>'id'],
                                                                                                        'only'=>['index']
                                                                                                    ]);                   
    
    Route::post('/report/rkpd/reportrkpdperubahanopd/search',['uses'=>'Report\ReportRKPDPerubahanOPDController@search','as'=>'reportrkpdperubahanopd.search']);              
    Route::post('/report/rkpd/reportrkpdperubahanopd/filter',['uses'=>'Report\ReportRKPDPerubahanOPDController@filter','as'=>'reportrkpdperubahanopd.filter']);                  
    Route::get('/report/rkpd/reportrkpdperubahanopd/printtoexcel',['uses'=>'Report\ReportRKPDPerubahanOPDController@printtoexcel','as'=>'reportrkpdperubahanopd.printtoexcel']);  
    
    //Report - PEMBAHASAN RKPD PERUBAHAN PER OPD
    Route::resource('/report/rkpd/reportpembahasanrkpdpopd','Report\ReportPembahasanRKPDPOPDController',[
                                                                                                        'parameters'=>['reportpembahasanrkpdpopd'=>'id'],
                                                                                                        'only'=>['index']
                                                                                                    ]);                   
    
    Route::post('/report/rkpd/reportpembahasanrkpdpopd/search',['uses'=>'Report\ReportPembahasanRKPDPOPDController@search','as'=>'reportpembahasanrkpdpopd.search']);              
    Route::post('/report/rkpd/reportpembahasanrkpdpopd/filter',['uses'=>'Report\ReportPembahasanRKPDPOPDController@filter','as'=>'reportpembahasanrkpdpopd.filter']);                  
    Route::get('/report/rkpd/reportpembahasanrkpdpopd/printtoexcel',['uses'=>'Report\ReportPembahasanRKPDPOPDController@printtoexcel','as'=>'reportpembahasanrkpdpopd.printtoexcel']);  

    //Report - RENCANA KERJA OPD / SKPD - PROGRAM RKPD PERUBAHAN PER OPD
    Route::resource('/report/rkpd/reportprogramperubahanopd','Report\ReportProgramPerubahanOPDController',[
                                                                                                            'parameters'=>['reportprogramperubahanopd'=>'id'],
                                                                                                            'only'=>['index']
                                                                                                        ]);                   
    
    Route::post('/report/rkpd/reportprogramperubahanopd/search',['uses'=>'Report\ReportProgramPerubahanOPDController@search','as'=>'reportprogramperubahanopd.search']);              
    Route::post('/report/rkpd/reportprogramperubahanopd/filter',['uses'=>'Report\ReportProgramPerubahanOPDController@filter','as'=>'reportprogramperubahanopd.filter']);                  
    Route::get('/report/rkpd/reportprogramperubahanopd/printtoexcel',['uses'=>'Report\ReportProgramPerubahanOPDController@printtoexcel','as'=>'reportprogramperubahanopd.printtoexcel']);  

    //setting - permissions    
    Route::resource('/setting/permissions','Setting\PermissionsController',[
                                                                            'parameters'=>['permissions'=>'id'],
                                                                            'only'=>['index','show','create','store','destroy']
                                                                        ]);               
    
    Route::get('/setting/permissions/paginate/{id}',['uses'=>'Setting\PermissionsController@paginate','as'=>'permissions.paginate']);    
    Route::post('/setting/permissions/search',['uses'=>'Setting\PermissionsController@search','as'=>'permissions.search']);          
    Route::post('/setting/permissions/changenumberrecordperpage',['uses'=>'Setting\PermissionsController@changenumberrecordperpage','as'=>'permissions.changenumberrecordperpage']);  
    Route::post('/setting/permissions/orderby',['uses'=>'Setting\PermissionsController@orderby','as'=>'permissions.orderby']);  
    
    //setting - roles
    Route::resource('/setting/roles','Setting\RolesController',['parameters'=>['roles'=>'id']]);           
    Route::get('/setting/roles/paginate/{id}',['uses'=>'Setting\RolesController@paginate','as'=>'roles.paginate']);    
    Route::post('/setting/roles/changenumberrecordperpage',['uses'=>'Setting\RolesController@changenumberrecordperpage','as'=>'roles.changenumberrecordperpage']);  
    Route::post('/setting/roles/orderby',['uses'=>'Setting\RolesController@orderby','as'=>'roles.orderby']);  
    Route::post('/setting/roles/storerolepermission', ['uses'=>'Setting\RolesController@storerolepermission','as'=>'roles.storerolepermission']);
    
    //setting - users
    Route::resource('/setting/users','Setting\UsersController',['parameters'=>['users'=>'id']])->middleware(['auth','role:superadmin']);           
    Route::get('/setting/users/paginate/{id}',['uses'=>'Setting\UsersController@paginate','as'=>'users.paginate'])->middleware(['auth','role:superadmin']);    
    Route::get('/setting/users/profil/{id}',['uses'=>'Setting\UsersController@profil','as'=>'users.profil']);    
    Route::put('/setting/users/updateprofil/{id}',['uses'=>'Setting\UsersController@updateprofil','as'=>'users.updateprofil']);        
    Route::post('/setting/users/changenumberrecordperpage',['uses'=>'Setting\UsersController@changenumberrecordperpage','as'=>'users.changenumberrecordperpage'])->middleware(['auth','role:superadmin']);  
    Route::post('/setting/users/orderby',['uses'=>'Setting\UsersController@orderby','as'=>'users.orderby'])->middleware(['auth','role:superadmin']); 
    Route::post('/setting/users/search',['uses'=>'Setting\UsersController@search','as'=>'users.search'])->middleware(['auth','role:superadmin']);    
    Route::post('/setting/users/filter',['uses'=>'Setting\UsersController@filter','as'=>'users.filter'])->middleware(['auth','role:superadmin']); 
    
    //setting - users bapelitbang
    Route::resource('/setting/usersbapelitbang','Setting\UsersBapelitbangController',['parameters'=>['usersbapelitbang'=>'id']]);           
    Route::get('/setting/usersbapelitbang/paginate/{id}',['uses'=>'Setting\UsersBapelitbangController@paginate','as'=>'usersbapelitbang.paginate']);        
    Route::post('/setting/usersbapelitbang/changenumberrecordperpage',['uses'=>'Setting\UsersBapelitbangController@changenumberrecordperpage','as'=>'usersbapelitbang.changenumberrecordperpage']);  
    Route::post('/setting/usersbapelitbang/orderby',['uses'=>'Setting\UsersBapelitbangController@orderby','as'=>'usersbapelitbang.orderby']); 
    Route::post('/setting/usersbapelitbang/search',['uses'=>'Setting\UsersBapelitbangController@search','as'=>'usersbapelitbang.search']);    
    Route::post('/setting/usersbapelitbang/filter',['uses'=>'Setting\UsersBapelitbangController@filter','as'=>'usersbapelitbang.filter']);

    //setting - users OPD
    Route::resource('/setting/usersopd','Setting\UsersOPDController',['parameters'=>['usersopd'=>'id']]);           
    Route::post('/setting/usersopd/store1/{id}',['uses'=>'Setting\UsersOPDController@store1','as'=>'usersopd.store1']);  
    Route::put('/setting/usersopd/changelocked/{id}',['uses'=>'Setting\UsersOPDController@changelocked','as'=>'usersopd.changelocked']);      
    Route::get('/setting/usersopd/paginate/{id}',['uses'=>'Setting\UsersOPDController@paginate','as'=>'usersopd.paginate']);
    Route::post('/setting/usersopd/changenumberrecordperpage',['uses'=>'Setting\UsersOPDController@changenumberrecordperpage','as'=>'usersopd.changenumberrecordperpage']);      
    Route::post('/setting/usersopd/orderby',['uses'=>'Setting\UsersOPDController@orderby','as'=>'usersopd.orderby']); 
    Route::post('/setting/usersopd/search',['uses'=>'Setting\UsersOPDController@search','as'=>'usersopd.search']);    
    Route::post('/setting/usersopd/filter',['uses'=>'Setting\UsersOPDController@filter','as'=>'usersopd.filter']);    
    Route::post('/setting/usersopd/storeuserpermission', ['uses'=>'Setting\UsersOPDController@storeuserpermission','as'=>'usersopd.storeuserpermission']);
    
    //setting - users DEWAN
    Route::resource('/setting/usersdewan','Setting\UsersDewanController',['parameters'=>['usersdewan'=>'id']]);           
    Route::post('/setting/usersdewan/store1/{id}',['uses'=>'Setting\UsersDewanController@store1','as'=>'usersdewan.store1']);  
    Route::get('/setting/usersdewan/paginate/{id}',['uses'=>'Setting\UsersDewanController@paginate','as'=>'usersdewan.paginate']);
    Route::post('/setting/usersdewan/changenumberrecordperpage',['uses'=>'Setting\UsersDewanController@changenumberrecordperpage','as'=>'usersdewan.changenumberrecordperpage']);      
    Route::post('/setting/usersdewan/orderby',['uses'=>'Setting\UsersDewanController@orderby','as'=>'usersdewan.orderby']); 
    Route::post('/setting/usersdewan/search',['uses'=>'Setting\UsersDewanController@search','as'=>'usersdewan.search']);    
    Route::post('/setting/usersdewan/filter',['uses'=>'Setting\UsersDewanController@filter','as'=>'usersdewan.filter']);    
    Route::post('/setting/usersdewan/storeuserpermission', ['uses'=>'Setting\UsersDewanController@storeuserpermission','as'=>'usersdewan.storeuserpermission']);
    
    //setting - users KECAMATAN
    Route::resource('/setting/userskecamatan','Setting\UsersKecamatanController',['parameters'=>['userskecamatan'=>'id']]);           
    Route::post('/setting/userskecamatan/store1/{id}',['uses'=>'Setting\UsersKecamatanController@store1','as'=>'userskecamatan.store1']);  

app/Models/Setting/GlobalSettingModel.php
<?php

namespace App\Models\Setting;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class GlobalSettingModel extends Model {
    use LogsActivity;
     /**
     * nama tabel model ini.
     *
     * @var string
     */
    protected $table = 'globalsetting';
    /**
     * primary key tabel ini.
     *
     * @var string
     */
    protected $primaryKey = 'globalsetting_id';
    /**
     * disable auto_increment.
     *
     * @var string
     */
    public $incrementing = true;
    /**
     * activated timestamps.
     *
     * @var string
     */
    public $timestamps = true;

    /**
     * make the model use another name than the default
     *
     * @var string
     */
    // protected static $logName = 'GlobalSettingController';
    /**
     * log the changed attributes for all these events 
     */
    // protected static $logAttributes = ['replace_it', 'replace_it'];
    /**
     * log changes to all the $fillable attributes of the model
     */
    // protected static $logFillable = true;

    //only the `deleted` event will get logged automatically
    // protected static $recordEvents = ['deleted'];

    public function writeToConfig ()
    {
        // Grab settings from database as a list
        $settings = $this::lists('globalsetting_key', 'globalsetting_value')->all();

        // Generate and save config file
        $filePath = config_path() . '/eplanning.php';
        $content = '<?php return ' . var_export($settings, true) . ';';
        File::put($filePath, $content);
    }
}

app/Models/Setting/Logs/LogViewerModel.php
<?php

namespace App\Models\Setting\Logs;

class LogViewerModel
{
    
}

resources/views/pages/limitless/setting/userskecamatan/datatable.blade.php
<div class="panel panel-flat border-top-lg border-top-info border-bottom-info">
    <div class="panel-heading">       
        <div class="panel-title">
            <h6 class="panel-title">&nbsp;</h6>
        </div>
        <div class="heading-elements">
            {!! Form::open(['url'=>'#','method'=>'post','class'=>'heading-form','id'=>'frmheading','name'=>'frmheading'])!!} 
                <div class="form-group">
                    {!!Form::select('numberRecordPerPage',['1'=>1,'5'=>5,'10'=>10,'15'=>15,'30'=>30,'50'=>50],$numberRecordPerPage,['id'=>'numberRecordPerPage','class'=>'form-control','style'=>'width:70px'])!!}                        
                </div> 
                <div class="form-group">
                    <a href="{!!route('userskecamatan.create')!!}" class="btn btn-info btn-xs" title="Tambah User Kecamatan">
                        <i class="icon-googleplus5"></i>
                    </a>
                </div> 
            {!! Form::close()!!}
        </div>       
    </div>
    @if (count($data) > 0)
    <div class="table-responsive"> 
        <table id="data" class="table table-striped table-hover">
            <thead>
                <tr class="bg-teal-700">
                    <th width="55">NO</th>
                    <th></th>
                    <th width="100">
                        <a class="column-sort text-white" id="col-id" data-order="{{$direction}}" href="#">
                            ID  
                        </a>                                             
                    </th>                     
                    <th>
                        <a class="column-sort text-white" id="col-username" data-order="{{$direction}}" href="#">
                            USERNAME  
                        </a>                                             
                    </th>
                    <th>
                        <a class="column-sort text-white" id="col-nama" data-order="{{$direction}}" href="#">
                            NAMA
                        </a>                                             
                    </th>
                    <th>
                        <a class="column-sort text-white" id="col-email" data-order="{{$direction}}" href="#">
                            EMAIL  
                        </a>                                             
                    </th>
                    <th width="70">THEME</th>
                    <th width="100">AKSI</th>
                </tr>
            </thead>
            <tbody>                    
            @foreach ($data as $key=>$item)
                <tr>
                    <td>
                        {{ ($data->currentpage()-1) * $data->perpage() + $key + 1 }}    
                    </td>                  
                    <th><img src="{!!asset($item->foto)!!}" alt="{{$item->username}}" height="50"></th>
                    <td>{{$item->id}}</td>
                    <td>{{$item->username}}</td> 
                    <td>{{$item->name}}</td> 
                    <td>{{$item->email}}</td> 
                    <td>{{$item->theme}}</td> 
                    <td>
                        <ul class="icons-list">
                            <li class="text-primary-600">
                                <a class="btnShow" href="{{route('userskecamatan.show',['id'=>$item->id])}}" title="Detail Data User Kecamatan">
                                    <i class='icon-eye'></i>
                                </a>  
                            </li>
                            <li class="text-primary-600">
                                <a class="btnEdit" href="{{route('userskecamatan.edit',['id'=>$item->id])}}" title="Ubah Data User Kecamatan">
                                    <i class='icon-pencil7'></i>
                                </a>  
                            </li>
                            <li class="text-danger-600">
                                <a class="btnDelete" href="javascript:;" title="Hapus Data User Kecamatan" data-id="{{$item->id}}" data-url="{{route('userskecamatan.index')}}">
                                    <i class='icon-trash'></i>
                                </a> 
                            </li>
                        </ul>
                    </td>
                </tr>
            @endforeach                    
            </tbody>
        </table>               
    </div>
    <div class="panel-body border-top-info text-center" id="paginations">
        {{$data->links('layouts.limitless.l_pagination')}}               
    </div>
    @else
    <div class="panel-body">
        <div class="alert alert-info alert-styled-left alert-bordered">
            <span class="text-semibold">Info!</span>
            Belum ada data yang bisa ditampilkan.
        </div>
    </div>   
    @endif            
</div>

resources/views/pages/limitless/setting/userskecamatan/datatablekecamatan.blade.php
<div class="panel panel-flat border-top-lg border-top-info border-bottom-info">
    <div class="panel-heading">       
        <div class="panel-title">
            <h6 class="panel-title">DAFTAR KECAMATAN</h6>
        </div>        
    </div>
    @if (count($datakecamatan) > 0)
    <div class="table-responsive"> 
        <table id="data" class="table table-striped table-hover">
            <thead>
                <tr class="bg-teal-700">
                    <th width="100">                      
                        ID                                     
                    </th>                     
                    <th>                        
                        TA                          
                    </th>
                    <th>                        
                        KODE                   
                    </th>
                    <th>
                        NAMA KECAMATAN                     
                    </th>
                    <th width="100">AKSI</th>
                </tr>
            </thead>
            <tbody>                    
            @foreach ($datakecamatan as $key=>$item)
                <tr>                   
                    <td>{{$item->userkecamatan}}</td>
                    <td>{{$item->ta}}</td> 
                    <td>{{$item->Kd_Kecamatan}}</td> 
                    <td>{{$item->Nm_Kecamatan}}</td> 
                    <td>
                        <ul class="icons-list">
                            <li class="text-danger-600">
                                <a class="btnDeleteKecamatan" href="javascript:;" title="Hapus Data User Kecamatan" data-id="{{$item->userkecamatan}}" data-url="{{route('userskecamatan.index')}}">
                                    <i class='icon-trash'></i>
                                </a> 
                            </li>
                        </ul>
                    </td>
                </tr>
            @endforeach                    
            </tbody>
        </table>               
    </div>
    @else
    <div class="panel-body">
        <div class="alert alert-info alert-styled-left alert-bordered">
            <span class="text-semibold">Info!</span>
            Belum ada data yang bisa ditampilkan.
        </div>
    </div>   
    @endif            
</div>

resources/views/pages/limitless/setting/userskecamatan/error.blade.php
@extends('layouts.limitless.l_main')
@section('page_title')
    USERS KECAMATAN
@endsection
@section('page_header')
    <i class="icon-users position-left"></i>
    <span class="text-semibold">
        USERS KECAMATAN
    </span>
@endsection
@section('page_info')
    @include('pages.limitless.setting.userskecamatan.info')
@endsection
@section('page_breadcrumb')
    <li><a href="{!!route('userskecamatan.index')!!}">USERS KECAMATAN</a></li>
    <li class="active">ERROR</li>
@endsection
@section('page_content')
<div class="alert alert-danger alert-styled-left alert-bordered">
    <button type="button" class="close" onclick="location.href='{{route('userskecamatan.index')}}'">×</button>
    {{$errormessage}}
</div>
@endsection

resources/views/pages/limitless/setting/userskecamatan/info.blade.php
<small class="display-block">          
    Modul untuk mengatur pengguna role Kecamatan.
</small>

resources/views/pages/limitless/setting/userskecamatan/show.blade.php
@extends('layouts.limitless.l_main')
@section('page_title')
    USERS KECAMATAN
@endsection
@section('page_header')
    <i class="icon-users position-left"></i>
    <span class="text-semibold"> 
        USERS KECAMATAN
    </span>     
@endsection
@section('page_info')
    @include('pages.limitless.setting.userskecamatan.info')
@endsection
@section('page_breadcrumb')
    <li><a href="#">SETTING</a></li>
    <li><a href="{!!route('userskecamatan.index')!!}">USERS KECAMATAN</a></li>
    <li class="active">DETAIL DATA</li>
@endsection
@section('page_content')
<div class="row">    
    <div class="col-md-12">
        <div class="panel panel-flat border-top-info border-bottom-info">
            <div class="panel-heading">
                <h5 class="panel-title"> 
                    <i class="icon-eye"></i>  DATA USER KECAMATAN
                </h5>
                <div class="heading-elements">   
                    <a href="{{route('userskecamatan.create')}}" class="btn btn-info btn-icon heading-btn btnTambah" title="Tambah Data Kelompok Urusan">
                        <i class="icon-googleplus5"></i>
                    </a>
                    <a href="{{route('userskecamatan.edit',['id'=>$data->id])}}" class="btn btn-primary btn-icon heading-btn btnEdit" title="Ubah Data User Kecamatan">
                        <i class="icon-pencil7"></i>
                    </a>
                    <a href="javascript:;" title="Hapus Data User Kecamatan" data-id="{{$data->id}}" data-url="{{route('userskecamatan.index')}}" class="btn btn-danger btn-icon heading-btn btnDelete">
                        <i class='icon-trash'></i>
                    </a>
                    <a href="{!!route('userskecamatan.index')!!}" class="btn btn-default btn-icon heading-btn" title="keluar">
                        <i class="icon-close2"></i>
                    </a>            
                </div>
            </div>
            <div class="panel-body">
                <div class="row">                                      
                    <div class="col-md-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>ID: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->id}}</p>
                                </div>                            
                            </div>    
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>USERNAME: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->username}}</p>
                                </div>                            
                            </div> 
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>NAMA: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->name}}</p>
                                </div>                            
                            </div>  
                        </div>                        
                    </div>
                    <div class="col-md-6">
                        <div class="form-horizontal">     
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>EMAIL: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{$data->email}}</p>
                                </div>                            
                            </div> 
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>TGL. BUAT: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{Helper::tanggal('d/m/Y H:m',$data->created_at)}}</p>
                                </div>                            
                            </div> 
                            <div class="form-group">
                                <label class="col-md-4 control-label"><strong>TGL. UBAH: </strong></label>
                                <div class="col-md-8">
                                    <p class="form-control-static">{{Helper::tanggal('d/m/Y H:m',$data->updated_at)}}</p>
                                </div>                            
                            </div>          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <i class="icon-pencil7 position-left"></i> 
                    TAMBAH KECAMATAN TAHUN PERENCANAAN {{HelperKegiatan::getTahunPerencanaan()}}
                </h5>                
            </div>
            <div class="panel-body">
                {!! Form::open(['action'=>['Setting\UsersKecamatanController@store1',$data->id],'method'=>'post','class'=>'form-horizontal','id'=>'frmdata','name'=>'frmdata'])!!}                                                  
                    <div class="form-group">
                        <label class="col-md-2 control-label">Nama Kecamatan :</label> 
                        <div class="col-md-10">
                            <select name="PmKecamatanID" id="PmKecamatanID" class="select">
                                <option></option>
                                @foreach ($daftar_kecamatan as $k=>$item)
                                    <option value="{{$k}}">{{$item}}</option>
                                @endforeach
                            </select>                              
                        </div>
                    </div>                           
                    <div class="form-group">            
                        <div class="col-md-10 col-md-offset-2">                        
                            {{ Form::button('<b><i class="icon-floppy-disk "></i></b> SIMPAN', ['type' => 'submit', 'class' => 'btn btn-info btn-labeled btn-xs'] ) }}
                        </div>
                    </div>
                {!! Form::close()!!}
            </div>
        </div>
    </div>    
    <div class="col-md-12" id="divdatatable">
        @include('pages.limitless.setting.userskecamatan.datatablekecamatan')
    </div>
</div>
@endsection
@section('page_asset_js')
<script src="{!!asset('themes/limitless/assets/js/jquery-validation/jquery.validate.min.js')!!}"></script>
<script src="{!!asset('themes/limitless/assets/js/jquery-validation/additional-methods.min.js')!!}"></script>
<script src="{!!asset('themes/limitless/assets/js/select2.min.js')!!}"></script>
@endsection
@section('page_custom_js')
<script type="text/javascript">
$(document).ready(function () {
    //styling select
    $('#PmKecamatanID.select').select2({
        placeholder: "PILIH KECAMATAN",
        allowClear:true
    });  
    $(".btnDelete").click(function(ev) {
        if (confirm('Apakah Anda ingin menghapus Data User Kecamatan ini ?')) {
            let url_ = $(this).attr("data-url");
            let id = $(this).attr("data-id");
            let token = $('meta[name="csrf-token"]').attr('content');
            $.ajax({            
                type:'post',
                url:url_+'/'+id,
                dataType: 'json',
                data: {
                    "_method": 'DELETE',
                    "_token": token,
                    "id": id,
                },
                success:function(data){ 
                    window.location.replace(url_);                        
                },
                error:function(xhr, status, error){
                    console.log('ERROR');
                    console.log(parseMessageAjaxEror(xhr, status, error));                           
                },
            });
        }
    });
    $('#frmdata').validate({
        ignore:[],
        rules: {                      
            PmKecamatanID : {
                required: true,
            }
        },
        messages : {            
            PmKecamatanID : {                
                required: "Mohon di pilih Anggota Kecamatan untuk user ini",
            }
        },        
    });   
    $("#divdatatable").on("click",".btnDeleteKecamatan", function(){
        if (confirm('Apakah Anda ingin menghapus Data Hak Akses pada Kecamatan ini ?')) {
            let url_ = $(this).attr("data-url");
            let id = $(this).attr("data-id");
            $.ajax({            
                type:'post',
                url:url_+'/'+id,
                dataType: 'json',
                data: {
                    "_method": 'DELETE',
                    "_token": token,
                    "id": id,
                    'userkecamatan':true
                },
                success:function(result)
                {                     
                    $('#divdatatable').html(result.datatable); 
                },
                error:function(xhr, status, error){
                    console.log('ERROR');
                    console.log(parseMessageAjaxEror(xhr, status, error));                           
                },
            });
        }        
    });
});
</script>
@endsection